fingerprint_method: "plugae"
fingerprint_type: "black-box"
seed: 42

cached_fingerprints_path: "cache/plugae/smoke_fingerprints.pth"
re_fingerprinting: true

query_path: "data/plugae_questions.csv"
num_queries: 1
copyright_token: "mkahg"
learning_rate: 0.1
epochs: 1
optimization_batch_size: 1
generation_batch_size: 1
