fingerprint_method: trap
fingerprint_type: black-box
seed: 42
cached_fingerprints_path: cache/v100_fingerprint_paper/trap/vicuna_shard_0.pth
re_fingerprinting: true
n_goals: 100
goal_offset: 0
goal_count: 34
prompt_seed: 41
string_type: number
string_length: 4
prompt_path: cache/v100_fingerprint_paper/trap/vicuna_prompts_target_seed_41_shard_0.csv
regenerate_prompts: true
test_n_times: 10
batch_size: 8
gcg_config: {num_steps: 1500, search_width: 512, batch_size: 512, topk: 256, n_replace: 1, seed: 42, use_prefix_cache: false, early_stop: false, filter_words_path: data/filter_words_number.csv}
